
spring:
  application:
    name: auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/clinic-realm

keycloak:
  realm: clinic
  auth-server-url: http://localhost:8080/auth/
  resource: auth-service
  credentials:
    secret: 6rpifPyl7fDhD65gCSpdjq1rCPq9IVwA
  bearer-only: true
  security-constraints:
    - authRoles:
        - admin
        - paciente
        - doctor
      securityCollections:
        - patterns:
            - /api/*


management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
