
spring:
  application:
    name: auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/clinic-realm

keycloak:
  auth-server-url: http://localhost:8080/realms/clinic-realm 
  realm: clinic-realm
  resource: clinic-app
  credentials:
    secret: EzQHVZN7v6trjSVNg4rntrizpKVV4PDx
  public-client: true
  bearer-only: true
  use-resource-role-mappings: true
  enable-basic-auth: true


management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
