
server:
  port: 8081

spring:
  application:
    name: auth-service

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/clinic-realm

keycloak:
  realm: clinic
  auth-server-url: http://keycloak:8080/auth/
  resource: auth-service
  credentials:
    secret: your-client-secret
  bearer-only: true
  security-constraints:
    - authRoles:
        - user
        - admin
      securityCollections:
        - patterns:
            - /api/*

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    health-check-url-path: /actuator/health
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
