spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallbackUri: forward:/fallback/auth

        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/appointments/**
          filters:
            - name: CircuitBreaker
              args:
                name: appointmentCircuitBreaker
                fallbackUri: forward:/fallback/appointments
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20

        - id: pacientes-service
          uri: lb://pacientes-service
          predicates:
            - Path=/pacientes/**
          filters:
            - name: CircuitBreaker
              args:
                name: pacientesCircuitBreaker
                fallbackUri: forward:/fallback/pacientes

        - id: specialist-service
          uri: lb://specialist-service
          predicates:
            - Path=/specialists/**
          filters:
            - name: CircuitBreaker
              args:
                name: specialistCircuitBreaker
                fallbackUri: forward:/fallback/specialists

        - id: incident-service
          uri: lb://incident-service
          predicates:
            - Path=/incidents/**
          filters:
            - name: CircuitBreaker
              args:
                name: incidentCircuitBreaker
                fallbackUri: forward:/fallback/incidents
  

resilience4j:
  circuitbreaker:
    instances:
      authCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
      appointmentCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
      pacientesCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
      specialistCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
      incidentCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3

  ratelimiter:
    instances:
      default:
        limitForPeriod: 100
        limitRefreshPeriod: 1s
        timeoutDuration: 3s

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
