spring:
  datasource:
    url: jdbc:mysql://mysql-informe:3306/informe_db  # Cambiar localhost por mysql-informe (nombre del servicio)
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: informe-service

  rabbitmq:
    host: rabbitmq    # En lugar de localhost
    port: 5672
    username: guest
    password: guest

  config:
    import: optional:config-server:http://config-server:8888

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/  # Usar nombre del servicio Eureka en Docker
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 30000
        loggerLevel: full
      paciente-service:
        url: http://paciente-service:8081
      doctor-service:
        url: http://doctor-service:8082
      clinica-service:
        url: http://clinica-service:8083
      cita-service:
        url: http://cita-service:8084