spring:
  main:
    allow-bean-definition-overriding: true


  datasource:
    url: jdbc:mysql://mmysql-pacientes:3306/pacientes_db
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/your-realm/protocol/openid-connect/certs

server:
  port: 8086

resilience4j:
  circuitbreaker:
    instances:
      usuariosService:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3

  timelimiter:
    instances:
      usuariosService:
        timeoutDuration: 5s

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakerevents,circuitbreaker
  endpoint:
    health:
      show-details: always
