server:
  port: 8090

spring:
  application:
    name: usuarios-service

  datasource:
    url: jdbc:mysql://mysql-db:3306/clinic_db
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ale123ferkatty@gmail.com
    password: frbilhcwbwznfljj
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
keycloak:
  server-url: http://keycloak:8080
  realm: clinic-realm
  admin:
    username: admin-clinic
    password: Admin123!
    client-id: admin-cli
